openapi: 3.0.3
info:
  title: FreeAPI
  description: >-
    # Boiler Plate Code

    Follow [these](https://github.com/ashutosh4336/express-boiler-plate-code#-installation) instructions for the installation and project setup.

    ## ğŸ Reporting issues

    If you find API issues or bugs when testing, please create an [issue](https://github.com/ashutosh4336/express-boiler-plate-code)
  version: 1.2.0
  contact: {}
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
